name: Peeps CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        # This confirms your Dockerfile actually works
        run: docker build -t peeps-test .

      - name: Run Django Tests
        # This runs the test we wrote in Step 1 inside the container
        run: docker run peeps-test python manage.py test